"""Official verified metadata registry for VietLabor AI legal corpus.

All metadata fields in this registry are verified directly against official records
from the Government Portal (vanban.chinhphu.vn) and National Legal Database (vbpl.vn).
"""

from __future__ import annotations
from typing import Any

VERIFIED_METADATA: dict[str, dict[str, Any]] = {
    "VBHN_18_2026": {
        "doc_id": "VBHN_18_2026",
        "document_no": "18/VBHN-VPQH",
        "doc_title": "Văn bản hợp nhất 18/VBHN-VPQH - Bộ luật Lao động",
        "document_type": "Văn bản hợp nhất",
        "issuer": "Văn phòng Quốc hội",
        "signer": "Lê Quang Mạnh",
        "effective_from": "2026-02-12",
        "effective_to": None,
        "status": "Còn hiệu lực",
        "official_source": "https://vanban.chinhphu.vn/?classid=0&docid=217002&pageid=27160",
    },
    "ND_145_2020": {
        "doc_id": "ND_145_2020",
        "document_no": "145/2020/NĐ-CP",
        "doc_title": "Nghị định 145/2020/NĐ-CP - Hướng dẫn Bộ luật Lao động về điều kiện lao động và quan hệ lao động",
        "document_type": "Nghị định",
        "issuer": "Chính phủ",
        "signer": "Nguyễn Xuân Phúc",
        "effective_from": "2021-02-01",
        "effective_to": None,
        "status": "Còn hiệu lực một phần",
        "official_source": "https://vanban.chinhphu.vn/default.aspx?docid=201967&pageid=27160",
    },
    "TT_10_2020": {
        "doc_id": "TT_10_2020",
        "document_no": "10/2020/TT-BLĐTBXH",
        "doc_title": "Thông tư 10/2020/TT-BLĐTBXH - Hướng dẫn nội dung HĐLĐ, Hội đồng thương lượng tập thể và nghề ảnh hưởng sinh sản",
        "document_type": "Thông tư",
        "issuer": "Bộ Lao động - Thương binh và Xã hội",
        "signer": "Đào Ngọc Dung",
        "effective_from": "2021-01-01",
        "effective_to": None,
        "status": "Còn hiệu lực",
        "official_source": "https://vbpl.vn/TW/Pages/vbpq-van-ban-goc.aspx?ItemID=146696",
    },
    "ND_293_2025": {
        "doc_id": "ND_293_2025",
        "document_no": "293/2025/NĐ-CP",
        "doc_title": "Nghị định 293/2025/NĐ-CP - Quy định mức lương tối thiểu đối với người lao động làm việc theo HĐLĐ",
        "document_type": "Nghị định",
        "issuer": "Chính phủ",
        "signer": "Hồ Đức Phớc",
        "effective_from": "2026-01-01",
        "effective_to": None,
        "status": "Còn hiệu lực",
        "official_source": "https://vanban.chinhphu.vn/?docid=215832&pageid=27160",
    },
    "ND_12_2022": {
        "doc_id": "ND_12_2022",
        "document_no": "12/2022/NĐ-CP",
        "doc_title": "Nghị định 12/2022/NĐ-CP - Quy định xử phạt vi phạm hành chính trong lĩnh vực lao động, bảo hiểm xã hội",
        "document_type": "Nghị định",
        "issuer": "Chính phủ",
        "signer": "Vũ Đức Đam",
        "effective_from": "2022-01-17",
        "effective_to": None,
        "status": "Còn hiệu lực",
        "official_source": "https://vanban.chinhphu.vn/?classid=0&docid=205182&pageid=27160",
    },
    "ND_337_2025": {
        "doc_id": "ND_337_2025",
        "document_no": "337/2025/NĐ-CP",
        "doc_title": "Nghị định 337/2025/NĐ-CP - Quy định về hợp đồng lao động điện tử",
        "document_type": "Nghị định",
        "issuer": "Chính phủ",
        "signer": "Phạm Thị Thanh Trà",
        "effective_from": "2026-01-01",
        "effective_to": None,
        "status": "CURRENT",
        "scope_tier": "core",
        "domain": "CORE_LABOR",
        "official_source": "https://vanban.chinhphu.vn/?classid=0&docid=216284&pageid=27160",
    },
    "TT_08_2026": {
        "doc_id": "TT_08_2026",
        "document_no": "08/2026/TT-BNV",
        "doc_title": "Thông tư 08/2026/TT-BNV - Hướng dẫn Nghị định 337/2025/NĐ-CP về hợp đồng lao động điện tử",
        "document_type": "Thông tư",
        "issuer": "Bộ Nội vụ",
        "signer": "Nguyễn Mạnh Khương",
        "effective_from": "2026-07-01",
        "effective_to": None,
        "status": "CURRENT",
        "scope_tier": "core",
        "domain": "CORE_LABOR",
        "official_source": "https://vanban.chinhphu.vn/?classid=0&docid=218200&pageid=27160",
    },
    # =========================================================================
    # EXTENDED WAVE 1 - RETIREMENT, UNEMPLOYMENT INSURANCE, FOREIGN WORKERS
    # =========================================================================
    "ND_135_2020": {
        "doc_id": "ND_135_2020",
        "document_no": "135/2020/NĐ-CP",
        "doc_title": "Nghị định 135/2020/NĐ-CP - Quy định về tuổi nghỉ hưu",
        "document_type": "Nghị định",
        "issuer": "Chính phủ",
        "signer": "Nguyễn Xuân Phúc",
        "issued_date": "2020-11-18",
        "effective_from": "2021-01-01",
        "effective_to": None,
        "status": "PARTIALLY_EFFECTIVE",
        "scope_tier": "extended",
        "domain": "RETIREMENT",
        "amended_by": "158/2025/NĐ-CP",
        "replaces": None,
        "official_source": "https://vanban.chinhphu.vn/default.aspx?docid=201886&pageid=27160",
    },
    "LVL_74_2025": {
        "doc_id": "LVL_74_2025",
        "document_no": "74/2025/QH15",
        "doc_title": "Luật Việc làm 74/2025/QH15 - Chế định Bảo hiểm thất nghiệp và việc làm",
        "document_type": "Luật",
        "issuer": "Quốc hội",
        "signer": "Trần Thanh Mẫn",
        "issued_date": "2025-06-25",
        "effective_from": "2026-01-01",
        "effective_to": None,
        "status": "CURRENT",
        "scope_tier": "extended",
        "domain": "UNEMPLOYMENT_INSURANCE",
        "replaces": "38/2013/QH13",
        "official_source": "https://vbpl.vn/TW/Pages/vbpq-toanvan.aspx?ItemID=174000",
    },
    "ND_374_2025": {
        "doc_id": "ND_374_2025",
        "document_no": "374/2025/NĐ-CP",
        "doc_title": "Nghị định 374/2025/NĐ-CP - Quy định chi tiết thi hành Luật Việc làm về Bảo hiểm thất nghiệp",
        "document_type": "Nghị định",
        "issuer": "Chính phủ",
        "signer": "Phạm Minh Chính",
        "issued_date": "2025-12-28",
        "effective_from": "2026-01-01",
        "effective_to": None,
        "status": "CURRENT",
        "scope_tier": "extended",
        "domain": "UNEMPLOYMENT_INSURANCE",
        "replaces": "28/2015/NĐ-CP, 61/2020/NĐ-CP",
        "official_source": "https://vanban.chinhphu.vn/?classid=0&docid=216890&pageid=27160",
    },
    "ND_219_2025": {
        "doc_id": "ND_219_2025",
        "document_no": "219/2025/NĐ-CP",
        "doc_title": "Nghị định 219/2025/NĐ-CP - Quy định về người lao động nước ngoài làm việc tại Việt Nam",
        "document_type": "Nghị định",
        "issuer": "Chính phủ",
        "signer": "Lê Thành Long",
        "issued_date": "2025-09-15",
        "effective_from": "2025-11-01",
        "effective_to": None,
        "status": "CURRENT",
        "scope_tier": "extended",
        "domain": "FOREIGN_WORKER",
        "replaces": "152/2020/NĐ-CP, 70/2023/NĐ-CP",
        "official_source": "https://vanban.chinhphu.vn/?classid=0&docid=215240&pageid=27160",
    },
}


def get_verified_metadata(doc_id: str) -> dict[str, Any]:
    """Returns verified metadata for doc_id or empty dict with needs_verification flags."""
    if doc_id in VERIFIED_METADATA:
        return VERIFIED_METADATA[doc_id]
    return {
        "doc_id": doc_id,
        "document_no": None,
        "doc_title": None,
        "document_type": None,
        "issuer": None,
        "signer": None,
        "effective_from": None,
        "effective_to": None,
        "status": "needs_verification",
        "scope_tier": "extended",
        "domain": "UNKNOWN",
        "amends": None,
        "amended_by": None,
        "replaces": None,
        "replaced_by": None,
        "official_source": None,
    }
