[theme]
base = "light"
primaryColor = "#A5121B"
backgroundColor = "#FAF7F0"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#34302D"
font = "Times New Roman"

[server]
headless = true
port = 8501
address = "127.0.0.1"
enableCORS = true
enableXsrfProtection = true
runOnSave = false
enableStaticServing = true

[browser]
gatherUsageStats = false
